server:
  port: 9991
  
  

spring:
  application:
    name: CONFIG-SERVICE
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mangeshdhande70/micro-service-config
          clone-on-start: true   